### ISSUE TITLE
Program is reporting it has a virus.

### ISSUE THREAD

**Issue by tinseltunes** [esphome/esphome-flasher#92] opened 2021-12-01 00:47 UTC
Not sure if you've had this before.
Virustotal.com is reporting it has a virus.
Antiy-AVL - Trojan/Generic.ASMalwS.34493BB - Cyren  W64/S-d6d7eeed!Eldorado
And 
Zillya Trojan.Disco.Win32.1337 - Acronis (Static ML)

Is this something you want to look into?

**Comment by OttoWinter** [comment] 2022-02-13 21:31
Duplicate of https://github.com/esphome/esphome-flasher/issues/40

**Closed** 2022-02-13 21:31 UTC
