### ISSUE TITLE
Getting virus warning from VirusTotal on ESPHome-Flasher-1.3.0-Windows-x64.exe

### ISSUE THREAD

**Issue by Tor-Adi** [esphome/esphome-flasher#30] opened 2020-08-20 16:52 UTC
![image](https://user-images.githubusercontent.com/64157850/90801513-4551dd00-e316-11ea-96eb-f04120e76a37.png)

Tor-Adi

**Comment by sjude68** [comment] 2020-12-06 12:04
Even I got a virus warning while downloading.

**Comment by EugeneKorneev** [comment] 2020-12-23 15:41
[2 engines detected this file](https://www.virustotal.com/gui/file/008f6aa24d287b91254d36f1187189a126817c74ae4ac5a99f0b27a2b38bd80f/community)
008f6aa24d287b91254d36f1187189a126817c74ae4ac5a99f0b27a2b38bd80f
ESPHome-Flasher-1.3.0-Windows-x64.exe

**Comment by superkillared** [comment] 2021-03-19 14:56
I got an even worse result testing the windows x86 version
![image](https://user-images.githubusercontent.com/51251444/111799647-370e7400-8899-11eb-9fba-60d8449cb1b0.png)

**Comment by sjude68** [comment] 2021-03-20 04:53
Why is the virus file not yet removed.

**Comment by OttoWinter** [comment] 2021-03-20 07:24
This is a duplicate of other issues, I'm merging the discussions into #40.

See also https://github.com/esphome/esphome-flasher/issues/40#issuecomment-803265110 for more details. **These are false positives**.

**Closed by OttoWinter** 2021-03-20 07:24 UTC
