### ISSUE TITLE
Chrome is staying dangerous

### ISSUE THREAD

**Issue by Gidget19893161** [esphome/esphome-flasher#102] opened 2022-01-18 01:58 UTC
When downloading the latest version crome is stopping it as dangerous and not able to open it. Please see the screencap of the error. 

![image](https://user-images.githubusercontent.com/48937634/149857279-1a93f949-84fc-49b6-9137-f4b44d06d014.png)

**Comment by OttoWinter** [comment] 2022-02-13 21:30
Duplicate of https://github.com/esphome/esphome-flasher/issues/40

**Closed** 2022-02-13 21:30 UTC
